package mocks

import "github.com/stretchr/testify/mock"

// FlowFile is an autogenerated mock type for the FlowFile type
type FlowFile struct {
	mock.Mock
}

// Id provides a mock function with given fields:
func (_m *FlowFile) Id() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}
