package mocks

import "github.com/apache/gominifi/api"
import "github.com/stretchr/testify/mock"

// ProcessContext is an autogenerated mock type for the ProcessContext type
type ProcessContext struct {
	mock.Mock
}

// GetPropertyValue provides a mock function with given fields: property
func (_m *ProcessContext) GetPropertyValue(property *api.Property) api.PropertyValue {
	ret := _m.Called(property)

	var r0 api.PropertyValue
	if rf, ok := ret.Get(0).(func(*api.Property) api.PropertyValue); ok {
		r0 = rf(property)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(api.PropertyValue)
		}
	}

	return r0
}
