package mocks

import "github.com/stretchr/testify/mock"

// PropertyValue is an autogenerated mock type for the PropertyValue type
type PropertyValue struct {
	mock.Mock
}

// AsString provides a mock function with given fields:
func (_m *PropertyValue) AsString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
